import { MenuItem, Testimonial, SpecialOffer } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // SOUPS
  {
    id: 'soup-1',
    name: 'Tomato Soup',
    description: 'Classic creamy tomato soup infused with herbs.',
    price: 4.99,
    category: 'soups',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'soup-2',
    name: 'Hot and Sour Soup',
    description: 'Spicy and tangy broth with mixed vegetables. Add-on Chicken, Egg, or Shrimp for +$1.',
    price: 4.99,
    category: 'soups',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'soup-3',
    name: 'Sweet Corn Soup',
    description: 'Comforting soup loaded with sweet corn kernels. Add-on Chicken, Egg, or Shrimp for +$1.',
    price: 4.99,
    category: 'soups',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'soup-4',
    name: 'Manchow Soup',
    description: 'Classic Indo-Chinese thick soup topped with crispy fried noodles. Add-on Chicken, Egg, or Shrimp for +$1.',
    price: 4.99,
    category: 'soups',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },

  // VEG APPETIZERS
  {
    id: 'vegapp-1',
    name: 'Veg Samosa (2 pcs)',
    description: 'Crispy pastry filled with spiced potatoes and green peas.',
    price: 5.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=600&q=80',
    tag: 'Classic',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: false,
  },
  {
    id: 'vegapp-2',
    name: 'Veg Spring Rolls (5 pcs)',
    description: 'Stir-fried crunchy vegetables wrapped in a thin crisp pastry.',
    price: 5.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: false,
  },
  {
    id: 'vegapp-3',
    name: 'Veg Pakoda',
    description: 'Crisp, deep-fried fritters made with chickpea flour and assorted vegetables.',
    price: 7.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'vegapp-4',
    name: 'Crispy Potato Wedges',
    description: 'Thick-cut potato wedges seasoned with herbs and aromatic spices.',
    price: 4.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'vegapp-5',
    name: 'Mozzarella Cheese Sticks',
    description: 'Golden breaded mozzarella cheese sticks served with savory dipping sauce.',
    price: 5.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: false,
  },
  {
    id: 'vegapp-6',
    name: 'Gobi Manchurian',
    description: 'Crispy cauliflower florets tossed in a sweet, savory, and spicy Indo-Chinese dark glaze.',
    price: 12.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80',
    tag: 'Popular',
    spiceLevel: 2,
    isVegetarian: true,
    isGlutenFree: false,
  },

  // VEG ENTREES
  {
    id: 'vegentree-1',
    name: 'Dhal Makhani',
    description: 'Slow-cooked black lentils simmered with cream, butter, and mild spices.',
    price: 12.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'vegentree-2',
    name: 'Veg Korma',
    description: 'Mixed seasonal vegetables simmered in a rich, creamy coconut and cashew nut sauce.',
    price: 12.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'vegentree-3',
    name: 'Saag Paneer',
    description: 'Cottage cheese cubes cooked in a spiced, creamy spinach gravy.',
    price: 13.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'vegentree-4',
    name: 'Paneer Tikka Masala',
    description: 'Grilled cottage cheese cubes simmered in an aromatic spiced tomato-cream sauce.',
    price: 13.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    tag: "Chef's Special",
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'vegentree-5',
    name: 'Kadai Paneer',
    description: 'Cottage cheese cubes sautéed with bell peppers, onions, and ground spices in a wok.',
    price: 13.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'vegentree-6',
    name: 'Paneer Butter Masala',
    description: 'Paneer cottage cheese cooked in a rich, creamy, buttery tomato-onion sauce.',
    price: 13.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'vegentree-7',
    name: 'Channa Masala',
    description: 'Soft chickpeas simmered in a tangy onion, tomato, and spice masala.',
    price: 12.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'vegentree-8',
    name: 'Aloo Gobi',
    description: 'Classic comforting dry dish of potatoes and cauliflower florets with spices.',
    price: 12.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },

  // NON-VEG APPETIZERS
  {
    id: 'nonvegapp-1',
    name: 'Chicken 65 Boneless',
    description: 'Crispy, deep-fried chicken bites tossed with tempered curry leaves and green chilies.',
    price: 12.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    tag: 'Classic',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'nonvegapp-2',
    name: 'Chilli Chicken',
    description: 'Stir-fried chicken bites with bell peppers and onions in a spicy, savory Indo-Chinese sauce.',
    price: 12.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'nonvegapp-3',
    name: 'Chicken Manchurian',
    description: 'Crispy chicken bites tossed in a sweet, sour, and tangy Manchurian glaze.',
    price: 12.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'nonvegapp-4',
    name: "Drunk'n Fish",
    description: 'Crispy batter-fried fish fillets seasoned with our signature chef spices.',
    price: 16.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    tag: "Chef's Special",
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'nonvegapp-5',
    name: 'Kurkuree Momos',
    description: 'Crunchy, double-fried momo dumplings with a savory seasoned filling.',
    price: 12.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'nonvegapp-6',
    name: 'Masala Momos',
    description: 'Steamed momo dumplings tossed in a rich, spicy, and aromatic masala gravy.',
    price: 12.99,
    category: 'appetizers',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: false,
  },

  // NON-VEG ENTREES - Chicken
  {
    id: 'ch-entree-1',
    name: 'Curry Express Special Chicken Curry',
    description: 'Served with Steamed Basmati Rice. Our signature chicken curry slow-cooked with a special blend of home-style spices.',
    price: 14.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    tag: 'Classic',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'ch-entree-2',
    name: 'Murg Saagwala',
    description: 'Served with Steamed Basmati Rice. Tender chicken breast pieces simmered in a flavorful spinach gravy.',
    price: 14.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'ch-entree-3',
    name: 'Kadai Chicken',
    description: 'Served with Steamed Basmati Rice. Chicken cooked in a traditional wok with bell peppers, tomatoes, and freshly ground spices.',
    price: 14.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'ch-entree-4',
    name: 'Butter Chicken',
    description: 'Served with Steamed Basmati Rice. Tender chicken simmered in an indulgent, rich tomato cream gravy flavored with butter.',
    price: 14.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    tag: 'Popular',
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'ch-entree-5',
    name: 'Chicken Tikka Masala',
    description: 'Served with Steamed Basmati Rice. Grilled chicken pieces simmered in a spiced tomato cream sauce.',
    price: 14.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    tag: "Chef's Special",
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'ch-entree-6',
    name: 'Chicken Vindaloo',
    description: 'Served with Steamed Basmati Rice. Goan-style fiery hot chicken curry cooked with vinegar and red chili paste.',
    price: 14.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 3,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'ch-entree-7',
    name: 'Chicken Korma',
    description: 'Served with Steamed Basmati Rice. Tender chicken cooked in a mild, rich cashew nut and yogurt sauce.',
    price: 14.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'ch-entree-8',
    name: 'Madras Chicken',
    description: 'Served with Steamed Basmati Rice. A rich, aromatic, medium-spicy South Indian curry flavored with coconut milk and curry leaves.',
    price: 14.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'ch-entree-9',
    name: 'Chicken Chettinadu',
    description: 'Served with Steamed Basmati Rice. Highly spiced chicken cooked with roasted coconut, black pepper, and stone flower.',
    price: 14.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 3,
    isVegetarian: false,
    isGlutenFree: true,
  },

  // NON-VEG ENTREES - Seafood
  {
    id: 'sea-entree-1',
    name: 'Goan Fish Curry',
    description: 'Served with Steamed Basmati Rice. Traditional fish curry made with coconut, tamarind, and Kashmiri red chilies.',
    price: 15.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'sea-entree-2',
    name: 'Coastal Fish Curry',
    description: 'Served with Steamed Basmati Rice. A light and tangy fish curry cooked with fresh green chilies and raw mango flavor.',
    price: 15.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'sea-entree-3',
    name: 'Coastal Shrimp Curry',
    description: 'Served with Steamed Basmati Rice. Juicy shrimp simmered in a spiced coastal coconut milk gravy.',
    price: 16.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'sea-entree-4',
    name: 'Shrimp Vindaloo',
    description: 'Served with Steamed Basmati Rice. Tangy and super fiery shrimp curry with red chilies and vinegar.',
    price: 16.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 3,
    isVegetarian: false,
    isGlutenFree: true,
  },

  // NON-VEG ENTREES - Goat Curry
  {
    id: 'gt-entree-1',
    name: 'Goat Curry',
    description: 'Served with Steamed Basmati Rice. Succulent bone-in goat meat slow-simmered in an onion-tomato gravy.',
    price: 16.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'gt-entree-2',
    name: 'Goat Korma',
    description: 'Served with Steamed Basmati Rice. Goat meat cooked in a creamy cashew and cardamom flavored curry.',
    price: 16.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'gt-entree-3',
    name: 'Kadai Goat',
    description: 'Served with Steamed Basmati Rice. Bone-in goat sautéed in a traditional wok with fresh tomatoes, bell peppers, and spices.',
    price: 16.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'gt-entree-4',
    name: 'Goat Vindaloo',
    description: 'Served with Steamed Basmati Rice. Hot and tangy goat curry cooked with red chili paste, vinegar, and garlic.',
    price: 16.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 3,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'gt-entree-5',
    name: 'Goat Tikka Masala',
    description: 'Served with Steamed Basmati Rice. Goat meat chunks simmered in a creamy, spiced masala sauce.',
    price: 16.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'gt-entree-6',
    name: 'Madras Goat',
    description: 'Served with Steamed Basmati Rice. Aromatic South Indian style goat curry cooked with roasted coconut carvings.',
    price: 16.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'gt-entree-7',
    name: 'Mutton Rogan Josh',
    description: 'Served with Steamed Basmati Rice. Slow-braised mutton in a rich yogurt-based onion gravy with saffron and cardamom.',
    price: 16.99,
    category: 'entrees',
    image: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },

  // BURGER FUSIONS & INDO-MEXICAN & AMERICAN
  {
    id: 'fusion-1',
    name: 'Half Pound Cheese Burger (Beef/Chicken)',
    description: 'Juicy half-pound patty topped with melted cheese, lettuce, and tomatoes.',
    price: 12.99,
    category: 'fusions',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'fusion-2',
    name: 'Curry Express Special Burger (Beef/Chicken)',
    description: 'Signature burger infused with curry spices and topped with our special secret house sauce.',
    price: 12.99,
    category: 'fusions',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    tag: "Chef's Special",
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'fusion-3',
    name: 'BBQ Cheese Burger (Beef/Chicken)',
    description: 'Half-pound burger glazed with sweet, smoky barbecue sauce and loaded with melted cheddar cheese.',
    price: 12.99,
    category: 'fusions',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'fusion-4',
    name: 'Crispy Chicken Sandwich',
    description: 'Crispy, golden-fried seasoned chicken breast fillet served in a toasted bun with mayo.',
    price: 12.99,
    category: 'fusions',
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'fusion-5',
    name: 'Chicken Over Rice',
    description: 'Spiced chicken strips served over a bed of warm, seasoned basmati rice with garlic white sauce.',
    price: 12.99,
    category: 'fusions',
    image: 'https://images.unsplash.com/photo-1512151172736-7574f15945d9?auto=format&fit=crop&w=600&q=80',
    tag: 'Popular',
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'fusion-6',
    name: 'Quesadilla',
    description: 'Folded flour tortilla grilled to perfection and stuffed with melted cheese and fresh spices.',
    price: 6.99,
    category: 'fusions',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: false,
  },
  {
    id: 'fusion-7',
    name: 'Burrito',
    description: 'Flour tortilla wrapped with rice, beans, and delicious spiced fillings.',
    price: 3.99,
    category: 'fusions',
    image: 'https://images.unsplash.com/photo-1626700051175-6518c4793f06?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: false,
  },
  {
    id: 'fusion-8',
    name: 'Corn Dog',
    description: 'Crispy cornmeal battered sausage on a stick, deep-fried to a perfect golden brown.',
    price: 6.99,
    category: 'fusions',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'fusion-9',
    name: 'Nachos',
    description: 'Crunchy tortilla chips loaded with warm, melted cheese sauce.',
    price: 3.99,
    category: 'fusions',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: false,
  },

  // HYDERABADI DUM BIRYANI
  {
    id: 'biryani-1',
    name: 'Chicken Biryani',
    description: 'Aged basmati rice cooked in layers with saffron-infused chicken, fresh mint, and dum spices.',
    price: 14.99,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    tag: 'Classic',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'biryani-2',
    name: 'Chicken Gilma Biryani',
    description: 'Special fiery-spiced chicken biryani cooked with double-marinated chicken chunks.',
    price: 15.99,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    tag: "Chef's Special",
    spiceLevel: 3,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'biryani-3',
    name: 'Goat Biryani',
    description: 'Tender select goat cuts layered with spiced basmati rice and finished under dum pressure.',
    price: 15.99,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'biryani-4',
    name: 'Shrimp Biryani',
    description: 'Aged basmati rice infused with spiced shrimp and caramelized onions.',
    price: 15.99,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'biryani-5',
    name: 'Egg Biryani',
    description: 'Spiced boiled eggs layered with aromatic dum basmati rice and fresh herbs.',
    price: 12.99,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: false,
    isGlutenFree: true,
  },
  {
    id: 'biryani-6',
    name: 'Veg Biryani',
    description: 'Mixed seasonal vegetables layered with fragrant basmati rice and slow cooked under dum pressure.',
    price: 12.99,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'biryani-7',
    name: 'Paneer Biryani',
    description: 'Aromatic rice cooked in dum style with spiced soft cottage cheese paneer cubes.',
    price: 13.99,
    category: 'biryani',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: true,
    isGlutenFree: true,
  },

  // BREADS (Extras)
  {
    id: 'bread-1',
    name: 'Garlic Naan',
    description: 'Fresh tandoor flatbread brushed with crushed garlic, cilantro, and warm butter.',
    price: 3.00,
    category: 'extras',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: false,
  },
  {
    id: 'bread-2',
    name: 'Butter Naan',
    description: 'Freshly baked leavened flatbread brushed generously with warm butter.',
    price: 2.50,
    category: 'extras',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: false,
  },
  {
    id: 'bread-3',
    name: 'Malabar Paratha',
    description: 'South Indian style multi-layered flakey flatbread cooked on a flat griddle.',
    price: 2.00,
    category: 'extras',
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: false,
  },

  // DESSERTS (Extras)
  {
    id: 'dessert-1',
    name: 'Rasamalai',
    description: 'Soft cottage cheese dumplings poached in cardamom and saffron-infused milk syrup.',
    price: 5.99,
    category: 'extras',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'dessert-2',
    name: 'Gulab Jamun',
    description: 'Deep-fried golden milk dough balls soaked in sweet, fragrant cardamom sugar syrup.',
    price: 5.99,
    category: 'extras',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: false,
  },
  {
    id: 'dessert-3',
    name: 'Rice Kheer',
    description: 'Traditional slow-cooked Indian rice pudding garnished with almonds and cashews.',
    price: 4.99,
    category: 'extras',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: true,
  },

  // BEVERAGES (Extras)
  {
    id: 'bev-1',
    name: 'Strawberry Lassi',
    description: 'Creamy yogurt drink blended with fresh sweet strawberries.',
    price: 4.99,
    category: 'extras',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'bev-2',
    name: 'Mango Lassi',
    description: 'Creamy, popular yogurt drink blended with sweet alphonso mangoes.',
    price: 4.99,
    category: 'extras',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: true,
  },

  // INDO-CHINESE
  {
    id: 'chinese-1',
    name: 'Hakka Noodles',
    description: 'Wok-tossed noodles with colorful julienned vegetables and light soy. Add-on Chicken, Egg, Shrimp, or Paneer for +$2.',
    price: 12.99,
    category: 'chinese',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: true,
    isGlutenFree: false,
  },
  {
    id: 'chinese-2',
    name: 'Bombay Noodles',
    description: 'Spicy street-style wok noodles tossed with tangy house sauce. Add-on Chicken, Egg, Shrimp, or Paneer for +$2.',
    price: 12.99,
    category: 'chinese',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegetarian: true,
    isGlutenFree: false,
  },

  // KIDS MENU
  {
    id: 'kids-1',
    name: 'French Fries',
    description: 'Golden crispy potato french fries served hot.',
    price: 3.99,
    category: 'kids',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isGlutenFree: true,
  },
  {
    id: 'kids-2',
    name: 'Chicken Nuggets (5 pcs)',
    description: 'Golden crisp breaded chicken nuggets with choice of dipping sauce.',
    price: 4.99,
    category: 'kids',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'kids-3',
    name: 'Chicken Tenders',
    description: 'Deep-fried golden, crispy tender chicken strips.',
    price: 6.99,
    category: 'kids',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'kids-4',
    name: 'Chicken Wings',
    description: 'Tossed wings. Choice of sauce: BBQ, Hot Sauce, Mango Habanero, or Bourbon Teriyaki.',
    price: 6.99,
    category: 'kids',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegetarian: false,
    isGlutenFree: false,
  },
  {
    id: 'kids-5',
    name: 'Shrimp Nuggets',
    description: 'Crispy golden fried shrimp nuggets served with savory dipping sauce.',
    price: 6.99,
    category: 'kids',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: false,
    isGlutenFree: false,
  },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    rating: 5,
    comment: '"The best Indo-Chinese in Montgomery, TX! The Gobi Manchurian is perfectly crispy and seasoned. Exceptional quality."',
    author: 'Sarah Jenkins',
    date: '2 days ago',
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: '2',
    rating: 5,
    comment: '"Butter chicken that actually tastes like it was made with love. The Dum Biryani has perfect fragrance and spice levels."',
    author: 'Michael Chen',
    date: '1 week ago',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80'
  },
  {
    id: '3',
    rating: 5,
    comment: '"Awesome variety. The combination of Indian classics, burger fusions, and kids options is fantastic for the family."',
    author: 'Priya Sharma',
    date: '2 weeks ago',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80'
  }
];

export const SPECIAL_OFFERS: SpecialOffer[] = [
  {
    id: 'offer-1',
    title: 'Hyderabadi Family Combo',
    description: 'Feeds 4-6 people. Includes choice of 2 Curries, 2 Dum Biryanis, 4 Naans, and 2 Mango Lassis.',
    priceText: 'Starting at $54.99',
    priceValue: 54.99,
    tag: 'Family Value',
    tagColor: 'secondary',
    iconName: 'groups',
    itemsAdded: ['ch-entree-4', 'biryani-1', 'bread-2'],
  },
  {
    id: 'offer-2',
    title: 'Daily Lunch Box SpeciaL',
    description: 'A complete lunchtime meal box with a curry entrée, fragrant basmati rice, salad, and appetizers.',
    priceText: 'Only $14.95',
    priceValue: 14.95,
    tag: 'Daily 11:00 AM - 3:00 PM',
    tagColor: 'primary',
    iconName: 'lunch_dining',
    itemsAdded: ['ch-entree-4', 'bread-2'],
  }
];
